# Generated by Django 4.2.4 on 2023-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='nearbylocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
