# Generated by Django 4.2.4 on 2023-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_useradress_nearbylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='phonenumber',
            field=models.CharField(blank=True),
        ),
    ]
