# Generated by Django 4.2.4 on 2023-08-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0006_customuser_lastname_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='combos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kids',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='men',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='woman',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
