# Generated by Django 4.2.4 on 2023-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0007_product_combos_product_kids_product_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
