# Generated by Django 4.2.4 on 2023-08-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0008_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multipleimges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='photos/vareintproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_auth.productvariant')),
            ],
        ),
    ]
