# Generated by Django 4.2.4 on 2023-09-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0011_coupons_maximum_order_amount_the_discount_percenetage_applicable_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
