# Generated by Django 4.2.4 on 2023-09-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0012_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='maximum_order_amount_the_discount_percenetage_applicable_for',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
