# Generated by Django 4.2.4 on 2023-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0014_alter_coupons_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='linkfordata',
            field=models.URLField(blank=True, default=True, null=True),
        ),
    ]
