# Generated by Django 4.2.4 on 2023-09-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0015_banner_linkfordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='linkfordata',
            field=models.URLField(blank=True, null=True),
        ),
    ]
