# Generated by Django 4.2.4 on 2023-09-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0018_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='checkcolor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
