# Generated by Django 4.2.4 on 2023-09-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0020_remove_productvariant_checkcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_note', models.CharField(blank=True, max_length=120)),
                ('product_varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_auth.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
