# Generated by Django 4.2.4 on 2023-09-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0003_alter_useradress_phonenumber'),
        ('admin_auth', '0012_delete_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('paid_amount', models.FloatField(blank=True)),
                ('ordernote', models.CharField(blank=True, max_length=50)),
                ('total', models.FloatField()),
                ('order_total', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=True)),
                ('wallet_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tax', models.FloatField()),
                ('status', models.CharField(choices=[('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50)),
                ('ip', models.CharField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_auth.useradress')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_auth.coupons')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=60)),
                ('payement_method', models.CharField(max_length=200)),
                ('total_amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quandity', models.IntegerField(default=0)),
                ('product_price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('return_request', models.BooleanField(default=False)),
                ('return_accept', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payments')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_auth.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payments'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
