# Generated by Django 4.2.4 on 2023-09-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
