# Generated by Django 4.2.4 on 2023-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=50),
        ),
    ]
