# Generated by Django 4.2.4 on 2023-09-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed')], default='Order Confirmed', max_length=50),
        ),
    ]
