# Generated by Django 4.2.4 on 2023-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_is_paid_order_payement_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payement_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed')], default='Order Confirmed', max_length=50),
        ),
    ]
