# Generated by Django 4.2.4 on 2023-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_is_paid_remove_order_payement_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelnote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50),
        ),
    ]
