# Generated by Django 4.2.4 on 2023-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_cancelnote_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing')], default='Order Confirmed', max_length=50),
        ),
    ]
