# Generated by Django 4.2.4 on 2023-09-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Returned', 'Returned'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50),
        ),
    ]
