# Generated by Django 4.2.4 on 2023-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_orderproduct_retrunsingleordernote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested')], default='Order Confirmed', max_length=50),
        ),
    ]
