# Generated by Django 4.2.4 on 2023-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50),
        ),
    ]
