# Generated by Django 4.2.4 on 2023-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Return requested', 'Return requested')], default='Order Confirmed', max_length=50),
        ),
    ]
